# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f8qbGr7f67qKoaGL-8VcOAzaeQbQh2B8
"""

import matplotlib.pyplot as plt

from Example_812 import solution1
from Example_813 import solution2
from Example_814 import solution3
from Example_815 import solution4
from Example_816 import solution5


def main():
    print("\nSolution of Example 8.12: \n")
    solution1()
    print("\n")

    print("Solution of Example 8.13: \n")
    solution2()
    print("\n")

    print("Solution of Example 8.14: \n")
    solution3()
    print("\n")

    print("Solution of Example 8.15: \n")
    solution4()
    print("\n")

    print("Solution of Example 8.16: \n")
    solution5()
    print("\n")

    plt.show()


if __name__ == "__main__":
    main()